---
title: "Exercise: EDA on Penguins"
toc: true
format: 
  html:
    dir: ltr
  ipynb: default
---

Note: you can **Download** the notebook from the sidebar, where it says "**Jupyter**".

In this notebook exercise, we will conduct simple EDA steps on the popular penguins dataset.

### Load the dataset

The following will load the dataset automatically.

In [1]:
import seaborn as sns

In [2]:
# You don't have to download the dataset
# the following will download it for you
df = sns.load_dataset('penguins')

Dataset source: https://github.com/allisonhorst/palmerpenguins

In [13]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.099998,18.700001,181.0,3750.0,Male
1,Adelie,Torgersen,39.500000,17.400000,186.0,3800.0,Female
2,Adelie,Torgersen,40.299999,18.000000,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.700001,19.299999,193.0,3450.0,Female

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     342 non-null    float32
 3   bill_depth_mm      342 non-null    float32
 4   flipper_length_mm  342 non-null    float32
 5   body_mass_g        342 non-null    float32
 6   sex                333 non-null    category
dtypes: category(3), float32(4)
memory usage: 6.9 KB

In [15]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921932      17.151171         200.915207  4201.754395
std          5.459584       1.974793          14.061714   801.954529
min         32.099998      13.100000         172.000000  2700.000000
25%         39.224998      15.600000         190.000000  3550.000000
50%         44.450001      17.299999         197.000000  4050.000000
75%         48.500000      18.700001         213.000000  4750.000000
max         59.599998      21.500000         231.000000  6300.000000

# Step 1 Understand the Features

You can find information about this dataset here: https://www.kaggle.com/datasets/parulpandey/palmer-archipelago-antarctica-penguin-data

**Question: in your own words**:

1. describe each feature
2. mention its type (numeric or categorical)
3. write its name in Arabic

Please use a Markdown cell to write your answer:

INSERT ANSWER HERE

Hint: you can attach an image to illustrate what the features are.

<img src="https://github.com/allisonhorst/palmerpenguins/raw/main/man/figures/culmen_depth.png" width="400">

# Step 2

- Have a look at the columns and their values (`head`, `sample`, `tail`)
- Look at the technical information (`info`)

In [4]:
df.head()
df.sample(5, random_state=42)
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

# Step 3

1. Calculate count of missing values
1. Calculate the percentage of missing values
2. For each column, check and handle missing values. You may:
    2. fill with mean or median
    1. drop the rows
3. Check and handle duplicated rows
4. **If** you chose to drop missing values, how much data did you lose?

In [12]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921932      17.151171         200.915207  4201.754395
std          5.459584       1.974793          14.061714   801.954529
min         32.099998      13.100000         172.000000  2700.000000
25%         39.224998      15.600000         190.000000  3550.000000
50%         44.450001      17.299999         197.000000  4050.000000
75%         48.500000      18.700001         213.000000  4750.000000
max         59.599998      21.500000         231.000000  6300.000000

# Step 4: Data types conversion

- We shall convert the string types to `category` to preserve memory
- numeric types can be stored in less precision: `float32`

In [5]:
# Convert categorical columns to category type
df['island'] = df['island'].astype('category')
df['sex'] = df['sex'].astype('category')

# Convert numerical columns to float32
df['bill_length_mm'] = df['bill_length_mm'].astype('float32')
df['flipper_length_mm'] = df['flipper_length_mm'].astype('float32')
df['body_mass_g'] = df['body_mass_g'].astype('float32')

In [6]:
mem_usage_before = df.memory_usage(deep=True)

In [7]:
# convert categotical types
df['species'] = df['species'].astype('category')
# ...?
# ...?

In [8]:
# convert numerical types
df['bill_depth_mm'] = df['bill_depth_mm'].astype('float32')
# ...?
# ...?
# ...?

Calculate memory saved after type conversion

In [ ]:
mem_usage_after = ...?

In [10]:
print('memory saved:', (mem_usage_before - mem_usage_after).sum() // 1024, 'KB')

NameError: name 'mem_usage_after' is not defined

# Step 5: Detect inconsistency in categorical values

The categorical columns should be checked for any inconsistencies. For example. We look for lowercase, uppercase, or inconsistent use of codes (e.g., "M", "F") with non-codes (e.g., "Male", "Female")  in the `sex` column.

- hint: use `.unique()` to check the number of unique values in a column
- you can also use: `.value_counts()` to check the frequency of each value in a column

In [ ]:
# INSERT CODE HERE

# Step 6: Univariate Analysis

- Separate numerical from categorical columns (hint; use `df.select_dtypes()`)
- Look at the statistical information for each:
    - `df_num.describe().T`
    - `df_cat.describe().T`

In [ ]:
# INSERT CODE HERE

Use charts to plot `value_counts()` categorical variables:

1. plot `species` using bar plot
1. plot `island` using pie chart
1. plot `sex` using horizontal bar plot

In [ ]:
# INSERT CODE HERE

Plot numerical variables:

1. Boxplot: `bill_length_mm`
1. Histogram: `bill_depth_mm`
1. Boxplot: `flipper_length_mm`
1. Histogram: `body_mass_g`

In [ ]:
# INSERT CODE HERE

# Step 7: Bivariate Analysis

## Correlation between numerical features

Let's find out if there is any correlation between numerical features.

- Hint: you can use the `df.corr()` to find the correlation matrix.
- Hint: you can use `sns.heatmap()` to plot the correlation matrix
- Hint: you can use `sns.pairplot()` to visualize relationships.

In [ ]:
# INSERT CODE HERE

Question: Write down your observations based on the correlation heatmap.

**Observations:**

INSERT ANSWER HERE

Looking at these distributions, how hard do you think it would be to classify the penguins only using `"culmen depth"` and `"culmen length"`?

INSERT ANSWER HERE

# Feature Engineering

- We might try adding the feature `bill_size` which is the product of `bill_length` and `bill_depth` to see if it has any significance in the model.
- We might also try `bill_ratio` which is the ratio of `bill_length` to `bill_depth` to see if it has any significance in the model.

In [ ]:
# INSERT CODE HERE

Let's look at the correlation to see whether the newly created features are better.

1. Compute the correlation matrix
1. Select the `'body_mass_g'` column, sort it, and plot it using horizontal bar plot

In [ ]:
# INSERT CODE HERE
# This plots the correlation values for a specific column
# which is usually what we are interested in

# corr['body_mass_g'].sort_values().plot.barh()